- name: Enable CalmAv
  shell: |
    sudo apt-get install build-essential wget
    sudo apt-get install openssl libssl-dev libcurl4-openssl-dev zlib1g-dev libpng-dev libxml2-dev libjson-c-dev libbz2-dev libpcre3-dev ncurses-dev
    sudo apt-get install valgrind check check-devel
    wget https://www.clamav.net/downloads/production/clamav-0.103.0.tar.gz -P ~/.
    tar xzf ~/clamav-0.103.0.tar.gz
    cd ~/clamav-0.103.0
    sudo freshclam
    sudo mkdir /var/lib/clamav
    sudo systemctl start clamav-freshclam
  args:
    executable: /bin/bash
  ignore_errors: true
